/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface Idw3FactoryInterface extends utils.Interface {
  functions: {
    "createIdw3(string,bool)": FunctionFragment;
    "deployedIdw3s(uint256)": FunctionFragment;
    "evaluateIfUserHasIdw3()": FunctionFragment;
    "idw3Owners(address)": FunctionFragment;
    "idw3s(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "createIdw3"
      | "deployedIdw3s"
      | "evaluateIfUserHasIdw3"
      | "idw3Owners"
      | "idw3s"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createIdw3",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedIdw3s",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "evaluateIfUserHasIdw3",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "idw3Owners",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "idw3s",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "createIdw3", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployedIdw3s",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evaluateIfUserHasIdw3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "idw3Owners", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "idw3s", data: BytesLike): Result;

  events: {};
}

export interface Idw3Factory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Idw3FactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createIdw3(
      _vaultId: PromiseOrValue<string>,
      _isSentient: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deployedIdw3s(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    evaluateIfUserHasIdw3(overrides?: CallOverrides): Promise<[boolean]>;

    idw3Owners(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    idw3s(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  createIdw3(
    _vaultId: PromiseOrValue<string>,
    _isSentient: PromiseOrValue<boolean>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deployedIdw3s(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  evaluateIfUserHasIdw3(overrides?: CallOverrides): Promise<boolean>;

  idw3Owners(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  idw3s(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    createIdw3(
      _vaultId: PromiseOrValue<string>,
      _isSentient: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    deployedIdw3s(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    evaluateIfUserHasIdw3(overrides?: CallOverrides): Promise<boolean>;

    idw3Owners(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    idw3s(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createIdw3(
      _vaultId: PromiseOrValue<string>,
      _isSentient: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deployedIdw3s(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    evaluateIfUserHasIdw3(overrides?: CallOverrides): Promise<BigNumber>;

    idw3Owners(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    idw3s(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createIdw3(
      _vaultId: PromiseOrValue<string>,
      _isSentient: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deployedIdw3s(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    evaluateIfUserHasIdw3(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    idw3Owners(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    idw3s(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
