/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface Idw3Interface extends utils.Interface {
  functions: {
    "getVaultId()": FunctionFragment;
    "isSentient()": FunctionFragment;
    "modifyPseudoSwitch()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getVaultId" | "isSentient" | "modifyPseudoSwitch"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getVaultId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isSentient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "modifyPseudoSwitch",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "getVaultId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isSentient", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "modifyPseudoSwitch",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Idw3 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Idw3Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getVaultId(overrides?: CallOverrides): Promise<[string]>;

    isSentient(overrides?: CallOverrides): Promise<[boolean]>;

    modifyPseudoSwitch(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getVaultId(overrides?: CallOverrides): Promise<string>;

  isSentient(overrides?: CallOverrides): Promise<boolean>;

  modifyPseudoSwitch(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getVaultId(overrides?: CallOverrides): Promise<string>;

    isSentient(overrides?: CallOverrides): Promise<boolean>;

    modifyPseudoSwitch(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getVaultId(overrides?: CallOverrides): Promise<BigNumber>;

    isSentient(overrides?: CallOverrides): Promise<BigNumber>;

    modifyPseudoSwitch(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getVaultId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isSentient(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    modifyPseudoSwitch(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
